apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: nginx
    port: 80
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
